version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: gomod
    directory: /src/main/jni/core
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "github.com/metacubex/mihomo"
        update-types:
          - version-update:semver-major
      - dependency-name: "github.com/metacubex/*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
